project_id = "sqqpyjtvteciorjluctb"

[functions.send-contact-email]
verify_jwt = false

[functions.submit-material-form]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
