import { FormEvent } from "react";
import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { ArrowRight, BarChart3, Bath, BriefcaseBusiness, Building2, CalendarDays, Check, ChevronRight, Clock3, Hammer, HardHat, Mail, MapPin, Menu, Phone, Scissors, Sparkles, Star, Target, TrendingUp, Users, X } from "lucide-react";
import { useState } from "react";

export type DemoKind = "frisorsalong" | "byggforetag" | "konsultbolag";

const DemoBadge = () => <Link to="/#examples" className="fixed z-[70] left-4 bottom-4 rounded-full bg-slate-950 text-white text-xs font-semibold px-4 py-2 shadow-2xl hover:scale-105 transition-transform">Exempelsida av Fertekz IT · Tillbaka</Link>;

const MobileMenu = ({ links, dark = false }: { links: { label: string; href: string }[]; dark?: boolean }) => {
  const [open, setOpen] = useState(false);
  return <><button className="md:hidden" aria-label="Öppna meny" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button>{open && <div className={`absolute left-0 right-0 top-full p-5 shadow-xl md:hidden ${dark ? "bg-slate-950 text-white" : "bg-white"}`}>{links.map(link => <a key={link.href} href={link.href} onClick={() => setOpen(false)} className="block py-3 border-b border-current/10">{link.label}</a>)}</div>}</>;
};

const HairSalonDemo = () => {
  const nav = [{ label: "Behandlingar", href: "#behandlingar" }, { label: "Om salongen", href: "#om" }, { label: "Omdömen", href: "#omdomen" }, { label: "Kontakt", href: "#kontakt" }];
  const treatments = [{ name: "Klippning", text: "Personlig konsultation, tvätt, klippning och styling.", price: "från 595 kr", icon: Scissors }, { name: "Färg & slingor", text: "Skräddarsydd färg som passar din stil och hudton.", price: "från 1 290 kr", icon: Sparkles }, { name: "Styling", text: "Fön, lockar eller uppsättning för vardag och fest.", price: "från 495 kr", icon: Star }];
  return <div className="min-h-screen bg-[#fffaf7] text-[#352a27] font-sans"><Helmet><title>Klipp&Dax | Frisörsalong – Demo</title><meta name="robots" content="noindex, nofollow" /></Helmet><DemoBadge />
    <header className="relative sticky top-0 z-50 bg-[#fffaf7]/95 backdrop-blur border-b border-[#eadbd4]"><div className="max-w-6xl mx-auto px-6 h-20 flex items-center justify-between"><a href="#top" className="font-serif text-2xl font-bold">Klipp&Dax</a><nav className="hidden md:flex gap-7 text-sm">{nav.map(item => <a key={item.href} href={item.href} className="hover:text-[#a55f52]">{item.label}</a>)}</nav><a href="#kontakt" className="hidden md:inline-flex rounded-full bg-[#a55f52] text-white px-5 py-2.5 text-sm font-semibold">Boka tid</a><MobileMenu links={nav} /></div></header>
    <main id="top"><section className="min-h-[700px] grid lg:grid-cols-2"><div className="px-7 sm:px-14 lg:pl-[max(3.5rem,calc((100vw-72rem)/2))] py-24 flex flex-col justify-center"><span className="uppercase tracking-[.25em] text-xs text-[#a55f52] font-semibold">Frisörsalong i Eskilstuna</span><h1 className="font-serif text-5xl sm:text-7xl leading-[1.05] mt-5 mb-7">Ditt hår.<br/>Din stil.<br/><em className="text-[#a55f52]">Din stund.</em></h1><p className="text-lg text-[#735f59] max-w-xl mb-8">På Klipp&Dax får du en frisörupplevelse med omtanke, hantverk och tid för dig. Vi skapar en look som känns lika bra som den ser ut.</p><div className="flex flex-wrap gap-3"><a href="#kontakt" className="rounded-full bg-[#a55f52] text-white px-7 py-3.5 font-semibold">Boka din tid</a><a href="#behandlingar" className="rounded-full border border-[#a55f52] px-7 py-3.5 font-semibold">Se behandlingar</a></div></div><div className="relative min-h-[500px] bg-gradient-to-br from-[#f0d9d0] via-[#d9aaa0] to-[#a55f52] overflow-hidden"><div className="absolute inset-10 border border-white/40 rounded-[10rem_2rem_10rem_2rem]"/><Scissors className="absolute h-40 w-40 text-white/30 top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2"/><div className="absolute bottom-10 left-10 bg-white/90 backdrop-blur rounded-2xl p-5 shadow-xl"><div className="flex text-[#a55f52] mb-1"><Star className="h-4 w-4 fill-current"/><Star className="h-4 w-4 fill-current"/><Star className="h-4 w-4 fill-current"/><Star className="h-4 w-4 fill-current"/><Star className="h-4 w-4 fill-current"/></div><p className="font-serif text-lg">“Så nöjd – varje gång.”</p><p className="text-xs text-[#735f59]">— Amanda, stamkund</p></div></div></section>
      <section id="behandlingar" className="py-24 px-6 max-w-6xl mx-auto"><div className="text-center max-w-2xl mx-auto mb-14"><span className="text-[#a55f52] text-sm font-semibold">BEHANDLINGAR</span><h2 className="font-serif text-4xl sm:text-5xl mt-3">Hitta din nya favoritlook</h2></div><div className="grid md:grid-cols-3 gap-6">{treatments.map(item => {const Icon=item.icon; return <article key={item.name} className="bg-white rounded-[2rem] p-8 shadow-[0_20px_60px_rgba(90,57,48,.08)]"><Icon className="h-8 w-8 text-[#a55f52] mb-8"/><h3 className="font-serif text-2xl mb-3">{item.name}</h3><p className="text-[#735f59] text-sm min-h-16">{item.text}</p><div className="mt-7 pt-5 border-t border-[#eadbd4] flex justify-between items-center"><strong>{item.price}</strong><a href="#kontakt" className="text-[#a55f52] text-sm font-semibold">Boka <ChevronRight className="inline h-4 w-4"/></a></div></article>})}</div></section>
      <section id="om" className="bg-[#3c2d29] text-white py-24 px-6"><div className="max-w-6xl mx-auto grid lg:grid-cols-2 gap-14 items-center"><div className="aspect-[4/3] rounded-[3rem_1rem_3rem_1rem] bg-gradient-to-br from-[#8f5b51] to-[#d8aaa0] flex items-center justify-center"><Sparkles className="h-28 w-28 text-white/40"/></div><div><span className="text-[#e7bbb0] text-sm font-semibold">OM STUDIO LYSTER</span><h2 className="font-serif text-4xl sm:text-5xl mt-3 mb-6">En salong där du kan landa</h2><p className="text-white/70 leading-relaxed mb-6">Vi tror på personliga möten, ärliga råd och hållbara resultat. Därför börjar varje besök med en konsultation där vi lyssnar på dina önskemål och lär känna ditt hår.</p><ul className="space-y-3">{["Erfarna och utbildade frisörer", "Produkter valda med omsorg", "Lugn miljö mitt i Eskilstuna"].map(text => <li key={text} className="flex gap-3"><Check className="text-[#e7bbb0]"/>{text}</li>)}</ul></div></div></section>
      <section id="omdomen" className="py-24 px-6 text-center"><p className="text-[#a55f52] text-2xl tracking-widest mb-5">★★★★★</p><blockquote className="font-serif text-3xl sm:text-5xl max-w-4xl mx-auto leading-tight">“Jag blir alltid lyssnad på och går härifrån med precis den känsla jag hoppades på.”</blockquote><p className="mt-6 text-[#735f59]">Elin · Kund sedan 2021</p></section>
      <section id="kontakt" className="bg-[#eedbd4] py-20 px-6"><div className="max-w-5xl mx-auto grid md:grid-cols-2 gap-12"><div><h2 className="font-serif text-4xl mb-5">Redo för en förändring?</h2><p className="text-[#735f59] mb-8">Skicka en bokningsförfrågan så återkommer vi med lediga tider.</p><div className="space-y-4"><p className="flex gap-3"><MapPin className="text-[#a55f52]"/> Kungsgatan 12, Eskilstuna</p><p className="flex gap-3"><Phone className="text-[#a55f52]"/> 016-123 45 67</p><p className="flex gap-3"><Clock3 className="text-[#a55f52]"/> Tis–fre 09–18 · Lör 10–15</p></div></div><DemoForm accent="#a55f52" button="Skicka bokningsförfrågan" /></div></section>
    </main><footer className="bg-[#3c2d29] text-white/60 py-8 px-6 text-center text-sm">© Klipp&Dax · Detta är en exempelsida skapad av Fertekz IT</footer></div>;
};

const BuilderDemo = () => {
  const nav = [{label:"Tjänster",href:"#tjanster"},{label:"Projekt",href:"#projekt"},{label:"Om oss",href:"#om"},{label:"Kontakt",href:"#kontakt"}];
  const services=[{name:"Badrum",text:"Kompletta badrumsrenoveringar med behöriga hantverkare.",icon:Bath},{name:"Kök",text:"Från idé och rivning till ett färdigt kök byggt för vardagen.",icon:Hammer},{name:"Tillbyggnad",text:"Mer plats med en trygg process från ritning till slutbesiktning.",icon:Building2}];
  return <div className="min-h-screen bg-[#f3f0e8] text-[#162019]"><Helmet><title>Sörmlands Bygg | Byggföretag – Demo</title><meta name="robots" content="noindex, nofollow"/></Helmet><DemoBadge/><header className="relative sticky top-0 z-50 bg-[#162019] text-white"><div className="max-w-7xl mx-auto h-20 px-6 flex items-center justify-between"><a href="#top" className="font-black text-xl">SÖRMLANDS <span className="text-[#f1ad32]">BYGG</span></a><nav className="hidden md:flex gap-8 text-sm">{nav.map(n=><a key={n.href} href={n.href}>{n.label}</a>)}</nav><a href="#kontakt" className="hidden md:block bg-[#f1ad32] text-[#162019] font-bold px-5 py-3">BEGÄR OFFERT</a><MobileMenu links={nav} dark/></div></header><main id="top">
    <section className="relative min-h-[720px] bg-gradient-to-r from-[#162019] via-[#223b2d] to-[#496b53] text-white flex items-center overflow-hidden"><div className="absolute inset-0 opacity-10" style={{backgroundImage:"linear-gradient(90deg,transparent 49%,#fff 50%),linear-gradient(transparent 49%,#fff 50%)",backgroundSize:"60px 60px"}}/><HardHat className="absolute right-[8%] h-80 w-80 text-white/5"/><div className="relative max-w-7xl mx-auto px-6 w-full"><div className="max-w-3xl"><span className="inline-block bg-[#f1ad32] text-[#162019] font-bold px-3 py-1.5 text-xs mb-6">BYGGFÖRETAG I SÖRMLAND</span><h1 className="text-5xl sm:text-7xl font-black leading-[1.02] mb-7">Vi bygger för<br/><span className="text-[#f1ad32]">nästa generation.</span></h1><p className="text-xl text-white/70 max-w-2xl mb-9">Trygga renoveringar och tillbyggnader med fast kontaktperson, tydlig tidplan och fem års garanti.</p><div className="flex flex-wrap gap-3"><a href="#kontakt" className="bg-[#f1ad32] text-[#162019] px-7 py-4 font-bold">FÅ KOSTNADSFRI OFFERT</a><a href="#projekt" className="border border-white/40 px-7 py-4 font-bold">SE VÅRA PROJEKT</a></div></div></div></section>
    <section className="bg-white border-b"><div className="max-w-7xl mx-auto px-6 py-6 grid grid-cols-2 md:grid-cols-4 gap-5">{[[Check,"F-skatt & försäkring"],[Users,"Egen kontaktperson"],[CalendarDays,"Tydlig tidplan"],[Star,"5 års garanti"]].map(([I,t])=>{const Icon=I as typeof Check;return <div key={t as string} className="flex items-center gap-3 font-bold text-sm"><Icon className="text-[#d9900d]"/>{t as string}</div>})}</div></section>
    <section id="tjanster" className="py-24 px-6 max-w-7xl mx-auto"><p className="text-[#b97600] font-bold text-sm">VAD VI GÖR</p><div className="flex flex-col md:flex-row justify-between gap-6 items-start mb-12"><h2 className="text-4xl sm:text-5xl font-black max-w-2xl">Hantverk som håller. Service du minns.</h2><p className="text-[#58645d] max-w-md">Vi samlar rätt yrkesgrupper och tar ansvar för hela projektet, så att du kan känna dig trygg från första mötet.</p></div><div className="grid md:grid-cols-3 gap-6">{services.map(s=>{const Icon=s.icon;return <article key={s.name} className="bg-white border-t-4 border-[#f1ad32] p-8 shadow-lg"><Icon className="h-10 w-10 mb-8"/><h3 className="text-2xl font-black mb-3">{s.name}</h3><p className="text-[#58645d] mb-8">{s.text}</p><a href="#kontakt" className="font-bold">BEGÄR OFFERT <ArrowRight className="inline h-4"/></a></article>})}</div></section>
    <section id="projekt" className="bg-[#162019] text-white py-24 px-6"><div className="max-w-7xl mx-auto"><div className="flex justify-between items-end mb-12"><div><p className="text-[#f1ad32] font-bold text-sm">UTVALDA PROJEKT</p><h2 className="text-4xl sm:text-5xl font-black mt-2">Byggt i Sörmland</h2></div></div><div className="grid md:grid-cols-2 gap-6">{[["Totalrenovering i Torshälla","Badrum · Kök · Ytskikt","from-[#536d5b] to-[#1d3526]"],["Tillbyggnad i Strängnäs","45 m² · Nyckelfärdigt","from-[#8f753f] to-[#3b3526]"]].map(([n,t,g])=><article key={n} className={`min-h-[350px] bg-gradient-to-br ${g} p-8 flex flex-col justify-end`}><span className="text-[#f1ad32] text-sm font-bold">{t}</span><h3 className="text-3xl font-black mt-2">{n}</h3></article>)}</div></div></section>
    <section id="om" className="py-24 px-6 max-w-6xl mx-auto grid lg:grid-cols-2 gap-14"><div><p className="text-[#b97600] font-bold text-sm">OM OSS</p><h2 className="text-4xl font-black mt-2 mb-6">Lokalt ansvar sedan 2008</h2><p className="text-[#58645d] leading-relaxed">Vi är ett sammansvetsat team av snickare, plattsättare och projektledare. För oss är ett lyckat projekt lika mycket en fråga om kommunikation som om hantverk.</p></div><div className="grid grid-cols-2 gap-4">{[["16+","år i branschen"],["240","slutförda projekt"],["4,9/5","kundbetyg"],["100%","lokalt team"]].map(([v,l])=><div key={l} className="bg-white p-6"><strong className="text-3xl block">{v}</strong><span className="text-sm text-[#58645d]">{l}</span></div>)}</div></section>
    <section id="kontakt" className="bg-[#f1ad32] py-20 px-6"><div className="max-w-6xl mx-auto grid md:grid-cols-2 gap-12"><div><p className="font-bold text-sm">KOSTNADSFRI OFFERT</p><h2 className="text-4xl sm:text-5xl font-black mt-2 mb-6">Vad vill du bygga?</h2><p className="text-[#47360e] mb-6">Beskriv projektet kort så återkommer vi inom en arbetsdag.</p><p className="flex gap-3 font-bold"><Phone/>016-555 12 00</p></div><DemoForm accent="#162019" button="SKICKA OFFERTFÖRFRÅGAN"/></div></section>
  </main><footer className="bg-[#162019] text-white/60 py-8 text-center text-sm">© Sörmlands Bygg · Detta är en exempelsida skapad av Fertekz IT</footer></div>;
};

const ConsultantDemo = () => {
  const nav=[{label:"Expertis",href:"#expertis"},{label:"Resultat",href:"#resultat"},{label:"Om oss",href:"#om"},{label:"Kontakt",href:"#kontakt"}];
  return <div className="min-h-screen bg-[#f7f9fc] text-[#0f1d3a]"><Helmet><title>Aero Konsult | Konsultbolag – Demo</title><meta name="robots" content="noindex, nofollow"/></Helmet><DemoBadge/><header className="relative sticky top-0 z-50 bg-white/95 backdrop-blur border-b"><div className="max-w-7xl mx-auto h-20 px-6 flex items-center justify-between"><a href="#top" className="font-bold text-xl">Aero Konsult<span className="text-[#2864ef]">.</span></a><nav className="hidden md:flex gap-8 text-sm font-medium">{nav.map(n=><a key={n.href} href={n.href}>{n.label}</a>)}</nav><a href="#kontakt" className="hidden md:block bg-[#0f1d3a] text-white px-5 py-3 rounded-md text-sm font-semibold">Boka ett möte</a><MobileMenu links={nav}/></div></header><main id="top">
    <section className="min-h-[700px] flex items-center px-6 relative overflow-hidden"><div className="absolute w-[550px] h-[550px] rounded-full bg-[#2864ef]/10 blur-3xl -right-20 top-0"/><div className="max-w-7xl mx-auto w-full grid lg:grid-cols-[1.2fr_.8fr] gap-14 items-center"><div><p className="text-[#2864ef] font-bold text-sm tracking-widest">STRATEGI · DATA · GENOMFÖRANDE</p><h1 className="text-5xl sm:text-7xl font-bold leading-[1.04] mt-5 mb-7">Strategi som blir<br/><span className="text-[#2864ef]">mätbara resultat.</span></h1><p className="text-xl text-[#61708d] max-w-2xl mb-9">Vi hjälper ägarledda bolag att fatta bättre beslut, skapa fokus och bygga en organisation som klarar nästa tillväxtfas.</p><div className="flex flex-wrap gap-3"><a href="#kontakt" className="bg-[#2864ef] text-white rounded-md px-7 py-4 font-semibold">Boka kostnadsfritt möte</a><a href="#resultat" className="border rounded-md px-7 py-4 font-semibold">Se våra resultat</a></div></div><div className="relative aspect-square bg-gradient-to-br from-[#dae5ff] to-[#8eacf2] rounded-[3rem] flex items-center justify-center"><TrendingUp className="h-40 w-40 text-[#2864ef]"/><div className="absolute -left-8 bottom-12 bg-white p-5 rounded-xl shadow-2xl"><span className="text-xs text-[#61708d]">Genomsnittlig tillväxt</span><strong className="block text-3xl text-[#2864ef]">+38%</strong></div></div></div></section>
    <section className="border-y bg-white"><div className="max-w-7xl mx-auto px-6 py-7 flex flex-wrap justify-center md:justify-between gap-7 text-[#78849b] font-bold"><span>NORDIC TECH</span><span>EKONOMIPARTNER</span><span>MÄLARBYGG</span><span>GREENFLOW</span><span>STUDIO NORD</span></div></section>
    <section id="expertis" className="py-24 px-6 max-w-7xl mx-auto"><div className="max-w-3xl mb-14"><p className="text-[#2864ef] font-bold text-sm">VÅR EXPERTIS</p><h2 className="text-4xl sm:text-5xl font-bold mt-3">Från komplexitet till tydlig riktning</h2></div><div className="grid md:grid-cols-3 gap-6">{[[Target,"Strategi","En konkret tillväxtplan med rätt prioriteringar och tydligt ansvar."],[BarChart3,"Analys & KPI","Beslutsunderlag och mätetal som visar vad som faktiskt driver värde."],[BriefcaseBusiness,"Ledningsstöd","Erfaren kraft i ledningsgruppen när förändringen ska genomföras."]].map(([I,n,t],i)=>{const Icon=I as typeof Target;return <article key={n as string} className="bg-white border rounded-xl p-8 hover:-translate-y-1 transition-transform"><span className="text-xs text-[#2864ef] font-bold">0{i+1}</span><Icon className="h-9 w-9 my-7 text-[#2864ef]"/><h3 className="text-2xl font-bold mb-3">{n as string}</h3><p className="text-[#61708d]">{t as string}</p></article>})}</div></section>
    <section id="resultat" className="bg-[#0f1d3a] text-white py-24 px-6"><div className="max-w-7xl mx-auto grid lg:grid-cols-2 gap-14"><div><p className="text-[#7da2ff] font-bold text-sm">KUNDCASE</p><h2 className="text-4xl sm:text-5xl font-bold mt-3 mb-6">Från spretig tillväxt till skalbar affär</h2><p className="text-white/60 text-lg">Ett snabbväxande tjänstebolag behövde skapa fokus och kontroll. På sex månader byggde vi en ny kommersiell modell och en gemensam styrning.</p></div><div className="grid grid-cols-2 gap-4">{[["+38%","återkommande intäkter"],["−21%","säljcykel"],["3,2×","pipeline"],["6 mån","till resultat"]].map(([v,l])=><div key={l} className="border border-white/15 rounded-xl p-6"><strong className="text-3xl text-[#7da2ff] block">{v}</strong><span className="text-sm text-white/60">{l}</span></div>)}</div></div></section>
    <section id="om" className="py-24 px-6 max-w-6xl mx-auto grid lg:grid-cols-2 gap-14 items-center"><div className="aspect-[4/3] rounded-3xl bg-gradient-to-br from-[#dce6ff] to-[#9eb8f5] flex items-center justify-center"><Users className="h-32 w-32 text-[#2864ef]/50"/></div><div><p className="text-[#2864ef] font-bold text-sm">OM NORTHLINE</p><h2 className="text-4xl font-bold mt-3 mb-6">Senior erfarenhet. Nära samarbete.</h2><p className="text-[#61708d] leading-relaxed mb-6">Vi är ett litet team av seniora rådgivare med bakgrund från ledande roller inom strategi, finans och försäljning. Hos oss arbetar du alltid direkt med den som gör jobbet.</p><ul className="space-y-3">{["Senior rådgivare i varje uppdrag","Fokus på genomförande, inte rapporter","Tydliga mål och löpande uppföljning"].map(t=><li key={t} className="flex gap-3"><Check className="text-[#2864ef]"/>{t}</li>)}</ul></div></section>
    <section id="kontakt" className="bg-[#e9effd] py-20 px-6"><div className="max-w-6xl mx-auto grid md:grid-cols-2 gap-12"><div><p className="text-[#2864ef] font-bold text-sm">FÖRSTA SAMTALET ÄR KOSTNADSFRITT</p><h2 className="text-4xl sm:text-5xl font-bold mt-3 mb-6">Vad vill ni förändra?</h2><p className="text-[#61708d] mb-8">Boka 30 minuter så utforskar vi utmaningen och ser om vi är rätt partner.</p><p className="flex gap-3 mb-3"><Mail className="text-[#2864ef]"/>kontakt@northline.se</p><p className="flex gap-3"><Phone className="text-[#2864ef]"/>08-410 240 00</p></div><DemoForm accent="#2864ef" button="Boka ett första samtal"/></div></section>
  </main><footer className="bg-[#0f1d3a] text-white/60 py-8 text-center text-sm">© Aero Konsult · Detta är en exempelsida skapad av Fertekz IT</footer></div>;
};

const DemoForm = ({ accent, button }: { accent: string; button: string }) => {
  const [sent,setSent]=useState(false); const submit=(e:FormEvent)=>{e.preventDefault();setSent(true)};
  return <form onSubmit={submit} className="bg-white text-slate-900 rounded-2xl p-6 shadow-xl space-y-4">{sent ? <div className="min-h-64 flex flex-col justify-center items-center text-center"><Check className="h-12 w-12 mb-4" style={{color:accent}}/><h3 className="text-xl font-bold">Tack för din förfrågan!</h3><p className="text-slate-500 text-sm mt-2">Detta är en demo, så inget meddelande skickades.</p></div> : <><div><label className="text-sm font-medium block mb-1">Namn</label><input required className="w-full border rounded-lg px-4 py-3" placeholder="Ditt namn"/></div><div><label className="text-sm font-medium block mb-1">E-post</label><input required type="email" className="w-full border rounded-lg px-4 py-3" placeholder="din@email.se"/></div><div><label className="text-sm font-medium block mb-1">Berätta kort</label><textarea required className="w-full border rounded-lg px-4 py-3 min-h-24" placeholder="Hur kan vi hjälpa dig?"/></div><button className="w-full text-white rounded-lg px-5 py-3.5 font-bold" style={{backgroundColor:accent}}>{button}</button></>}</form>;
};

const DemoSite = ({ kind }: { kind: DemoKind }) => kind === "frisorsalong" ? <HairSalonDemo /> : kind === "byggforetag" ? <BuilderDemo /> : <ConsultantDemo />;
export default DemoSite;
